banknifty_lot_size: 30
crude_oil_lot_size: 1
i_expiry_date_banknifty: 2026-04-30
i_expiry_date_crude_oil: 2026-02-17
i_expiry_date_nifty: 2026-04-21
i_expiry_date_sensex: 2026-04-16
i_inst_name_banknifty: BN
i_inst_name_crude_oil: C
i_inst_name_nifty: N
i_inst_name_sensex: S
i_instrument_type: null
i_stock_code_banknifty: BANKNIFTY
i_stock_code_crude_oil: CRUDEOIL
i_stock_code_nifty: NIFTY
i_stock_code_sensex: SENSEX
nifty_lot_size: 65
sensex_lot_size: 30
sensex_spot_token: 265
z_access_token: w9LI347LqPrxm32MSTA2OOMeF7WjMyqA
z_api_key: 7kbosahuhwl3muhk
z_api_secret: wu7d22otf07l91wxru3x5mzd3la52kd1
z_password: Hanush@786
z_public_token: null
z_request_token: null
z_tsecret: wu7d22otf07l91wxru3x5mzd3la52kd1
z_user_id: IX6094
nifty_spot_token: 256265
banknifty_spot_token: 260105
sensex_spot_token: 265
