name: Downside Stock Signal Scheduler

on:
  schedule:
    - cron: "25 9 * * 1-5"
  workflow_dispatch:

jobs:
  trigger-downside-stock-signal:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render downside stock signal
        run: |
          curl -X POST "https://hanush-backend-service1.onrender.com/api/downside-stock-signal-strategy/start"
